### ISSUE TITLE
无法登录ssh

### ISSUE THREAD

**Issue by githubusera2034324** [bin862324915/serv00-automation#1]
2024-08-05T11:25:04.4730528Z Current runner version: '2.317.0'
2024-08-05T11:25:04.4753753Z ##[group]Operating System
2024-08-05T11:25:04.4754371Z Ubuntu
2024-08-05T11:25:04.4754820Z 22.04.4
2024-08-05T11:25:04.4755163Z LTS
2024-08-05T11:25:04.4755455Z ##[endgroup]
2024-08-05T11:25:04.4755946Z ##[group]Runner Image
2024-08-05T11:25:04.4756382Z Image: ubuntu-22.04
2024-08-05T11:25:04.4756735Z Version: 20240730.2.0
2024-08-05T11:25:04.4757833Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240730.2/images/ubuntu/Ubuntu2204-Readme.md
2024-08-05T11:25:04.4759270Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240730.2
2024-08-05T11:25:04.4760116Z ##[endgroup]
2024-08-05T11:25:04.4760588Z ##[group]Runner Image Provisioner
2024-08-05T11:25:04.4761096Z 2.0.374.1
2024-08-05T11:25:04.4761429Z ##[endgroup]
2024-08-05T11:25:04.4763803Z ##[group]GITHUB_TOKEN Permissions
2024-08-05T11:25:04.4765381Z Actions: write
2024-08-05T11:25:04.4766104Z Attestations: write
2024-08-05T11:25:04.4766589Z Checks: write
2024-08-05T11:25:04.4767046Z Contents: write
2024-08-05T11:25:04.4767444Z Deployments: write
2024-08-05T11:25:04.4767869Z Discussions: write
2024-08-05T11:25:04.4768304Z Issues: write
2024-08-05T11:25:04.4768699Z Metadata: read
2024-08-05T11:25:04.4769092Z Packages: write
2024-08-05T11:25:04.4769520Z Pages: write
2024-08-05T11:25:04.4769884Z PullRequests: write
2024-08-05T11:25:04.4770313Z RepositoryProjects: write
2024-08-05T11:25:04.4770806Z SecurityEvents: write
2024-08-05T11:25:04.4771217Z Statuses: write
2024-08-05T11:25:04.4771605Z ##[endgroup]
2024-08-05T11:25:04.4775017Z Secret source: Actions
2024-08-05T11:25:04.4775628Z Prepare workflow directory
2024-08-05T11:25:04.5390405Z Prepare all required actions
2024-08-05T11:25:04.5549121Z Getting action download info
2024-08-05T11:25:04.7717946Z Download action repository 'actions/checkout@v2' (SHA:ee0669bd1cc54295c223e0bb666b733df41de1c5)
2024-08-05T11:25:04.8962348Z Download action repository 'actions/setup-python@v2' (SHA:e9aba2c848f5ebd159c070c61ea2c4e2b122355e)
2024-08-05T11:25:05.0597749Z Complete job name: ssh-login-notification
2024-08-05T11:25:05.1755631Z ##[group]Run actions/checkout@v2
2024-08-05T11:25:05.1756214Z with:
2024-08-05T11:25:05.1756748Z   repository: githubusera2034324/serv00-automation
2024-08-05T11:25:05.1757584Z   token: ***
2024-08-05T11:25:05.1757984Z   ssh-strict: true
2024-08-05T11:25:05.1758448Z   persist-credentials: true
2024-08-05T11:25:05.1758923Z   clean: true
2024-08-05T11:25:05.1759286Z   fetch-depth: 1
2024-08-05T11:25:05.1759685Z   lfs: false
2024-08-05T11:25:05.1760064Z   submodules: false
2024-08-05T11:25:05.1760483Z   set-safe-directory: true
2024-08-05T11:25:05.1760963Z ##[endgroup]
2024-08-05T11:25:05.3954149Z Syncing repository: githubusera2034324/serv00-automation
2024-08-05T11:25:05.3957386Z ##[group]Getting Git version info
2024-08-05T11:25:05.3959102Z Working directory is '/home/runner/work/serv00-automation/serv00-automation'
2024-08-05T11:25:05.3961505Z [command]/usr/bin/git version
2024-08-05T11:25:05.3962456Z git version 2.46.0
2024-08-05T11:25:05.3982003Z ##[endgroup]
2024-08-05T11:25:05.4003036Z Temporarily overriding HOME='/home/runner/work/_temp/08b26618-ab4f-4e03-8d2f-3ffb1a59740a' before making global git config changes
2024-08-05T11:25:05.4005818Z Adding repository directory to the temporary git global config as a safe directory
2024-08-05T11:25:05.4008571Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/serv00-automation/serv00-automation
2024-08-05T11:25:05.4043184Z Deleting the contents of '/home/runner/work/serv00-automation/serv00-automation'
2024-08-05T11:25:05.4045556Z ##[group]Initializing the repository
2024-08-05T11:25:05.4049829Z [command]/usr/bin/git init /home/runner/work/serv00-automation/serv00-automation
2024-08-05T11:25:05.4124842Z hint: Using 'master' as the name for the initial branch. This default branch name
2024-08-05T11:25:05.4126226Z hint: is subject to change. To configure the initial branch name to use in all
2024-08-05T11:25:05.4128111Z hint: of your new repositories, which will suppress this warning, call:
2024-08-05T11:25:05.4129267Z hint:
2024-08-05T11:25:05.4130105Z hint: 	git config --global init.defaultBranch <name>
2024-08-05T11:25:05.4131384Z hint:
2024-08-05T11:25:05.4133009Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2024-08-05T11:25:05.4135151Z hint: 'development'. The just-created branch can be renamed via this command:
2024-08-05T11:25:05.4136706Z hint:
2024-08-05T11:25:05.4137536Z hint: 	git branch -m <name>
2024-08-05T11:25:05.4139293Z Initialized empty Git repository in /home/runner/work/serv00-automation/serv00-automation/.git/
2024-08-05T11:25:05.4142045Z [command]/usr/bin/git remote add origin https://github.com/githubusera2034324/serv00-automation
2024-08-05T11:25:05.4179298Z ##[endgroup]
2024-08-05T11:25:05.4180150Z ##[group]Disabling automatic garbage collection
2024-08-05T11:25:05.4184536Z [command]/usr/bin/git config --local gc.auto 0
2024-08-05T11:25:05.4222400Z ##[endgroup]
2024-08-05T11:25:05.4223796Z ##[group]Setting up auth
2024-08-05T11:25:05.4229507Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-08-05T11:25:05.4261486Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-08-05T11:25:05.4594082Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-08-05T11:25:05.4622763Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-08-05T11:25:05.4853645Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2024-08-05T11:25:05.4887814Z ##[endgroup]
2024-08-05T11:25:05.4889266Z ##[group]Fetching the repository
2024-08-05T11:25:05.4898427Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +4f46d8bfede0e9d47a9df21e4f8f9369f3f2bf19:refs/remotes/origin/main
2024-08-05T11:25:05.8306234Z remote: Enumerating objects: 7, done.        
2024-08-05T11:25:05.8307035Z remote: Counting objects:  14% (1/7)        
2024-08-05T11:25:05.8307626Z remote: Counting objects:  28% (2/7)        
2024-08-05T11:25:05.8308421Z remote: Counting objects:  42% (3/7)        
2024-08-05T11:25:05.8309031Z remote: Counting objects:  57% (4/7)        
2024-08-05T11:25:05.8309555Z remote: Counting objects:  71% (5/7)        
2024-08-05T11:25:05.8310148Z remote: Counting objects:  85% (6/7)        
2024-08-05T11:25:05.8310640Z remote: Counting objects: 100% (7/7)        
2024-08-05T11:25:05.8311135Z remote: Counting objects: 100% (7/7), done.        
2024-08-05T11:25:05.8311751Z remote: Compressing objects:  20% (1/5)        
2024-08-05T11:25:05.8312292Z remote: Compressing objects:  40% (2/5)        
2024-08-05T11:25:05.8312919Z remote: Compressing objects:  60% (3/5)        
2024-08-05T11:25:05.8313421Z remote: Compressing objects:  80% (4/5)        
2024-08-05T11:25:05.8313930Z remote: Compressing objects: 100% (5/5)        
2024-08-05T11:25:05.8314557Z remote: Compressing objects: 100% (5/5), done.        
2024-08-05T11:25:05.8319833Z remote: Total 7 (delta 0), reused 3 (delta 0), pack-reused 0        
2024-08-05T11:25:05.8390887Z From https://github.com/githubusera2034324/serv00-automation
2024-08-05T11:25:05.8392344Z  * [new ref]         4f46d8bfede0e9d47a9df21e4f8f9369f3f2bf19 -> origin/main
2024-08-05T11:25:05.8417663Z ##[endgroup]
2024-08-05T11:25:05.8418904Z ##[group]Determining the checkout info
2024-08-05T11:25:05.8420171Z ##[endgroup]
2024-08-05T11:25:05.8421281Z ##[group]Checking out the ref
2024-08-05T11:25:05.8425378Z [command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
2024-08-05T11:25:05.8469721Z Switched to a new branch 'main'
2024-08-05T11:25:05.8473575Z branch 'main' set up to track 'origin/main'.
2024-08-05T11:25:05.8478635Z ##[endgroup]
2024-08-05T11:25:05.8514802Z [command]/usr/bin/git log -1 --format='%H'
2024-08-05T11:25:05.8542322Z '4f46d8bfede0e9d47a9df21e4f8f9369f3f2bf19'
2024-08-05T11:25:05.8927184Z ##[group]Run actions/setup-python@v2
2024-08-05T11:25:05.8927639Z with:
2024-08-05T11:25:05.8927985Z   python-version: 3.x
2024-08-05T11:25:05.8928636Z   token: ***
2024-08-05T11:25:05.8929000Z ##[endgroup]
2024-08-05T11:25:06.0048727Z Successfully setup CPython (3.12.4)
2024-08-05T11:25:06.0176993Z ##[group]Run python -m pip install --upgrade pip
2024-08-05T11:25:06.0177679Z [36;1mpython -m pip install --upgrade pip[0m
2024-08-05T11:25:06.0178169Z [36;1mpip install paramiko requests[0m
2024-08-05T11:25:06.0218442Z shell: /usr/bin/bash -e {0}
2024-08-05T11:25:06.0218946Z env:
2024-08-05T11:25:06.0219380Z   pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
2024-08-05T11:25:06.0220020Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib
2024-08-05T11:25:06.0220627Z ##[endgroup]
2024-08-05T11:25:06.7254515Z Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages (24.2)
2024-08-05T11:25:07.4047318Z Collecting paramiko
2024-08-05T11:25:07.4160540Z   Downloading paramiko-3.4.0-py3-none-any.whl.metadata (4.4 kB)
2024-08-05T11:25:07.4572522Z Collecting requests
2024-08-05T11:25:07.4599254Z   Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
2024-08-05T11:25:07.5092832Z Collecting bcrypt>=3.2 (from paramiko)
2024-08-05T11:25:07.5122903Z   Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.6 kB)
2024-08-05T11:25:07.7568011Z Collecting cryptography>=3.3 (from paramiko)
2024-08-05T11:25:07.7601601Z   Downloading cryptography-43.0.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
2024-08-05T11:25:07.7891723Z Collecting pynacl>=1.5 (from paramiko)
2024-08-05T11:25:07.7928706Z   Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl.metadata (8.6 kB)
2024-08-05T11:25:07.8727036Z Collecting charset-normalizer<4,>=2 (from requests)
2024-08-05T11:25:07.8757676Z   Downloading charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
2024-08-05T11:25:07.8958510Z Collecting idna<4,>=2.5 (from requests)
2024-08-05T11:25:07.8986957Z   Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
2024-08-05T11:25:07.9513851Z Collecting urllib3<3,>=1.21.1 (from requests)
2024-08-05T11:25:07.9546611Z   Downloading urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
2024-08-05T11:25:07.9806557Z Collecting certifi>=2017.4.17 (from requests)
2024-08-05T11:25:07.9834073Z   Downloading certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
2024-08-05T11:25:08.1044887Z Collecting cffi>=1.12 (from cryptography>=3.3->paramiko)
2024-08-05T11:25:08.1075803Z   Downloading cffi-1.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
2024-08-05T11:25:08.1260322Z Collecting pycparser (from cffi>=1.12->cryptography>=3.3->paramiko)
2024-08-05T11:25:08.1293253Z   Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
2024-08-05T11:25:08.1372421Z Downloading paramiko-3.4.0-py3-none-any.whl (225 kB)
2024-08-05T11:25:08.1445922Z Downloading requests-2.32.3-py3-none-any.whl (64 kB)
2024-08-05T11:25:08.1512986Z Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl (273 kB)
2024-08-05T11:25:08.1584057Z Downloading certifi-2024.7.4-py3-none-any.whl (162 kB)
2024-08-05T11:25:08.1643123Z Downloading charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
2024-08-05T11:25:08.1709695Z Downloading cryptography-43.0.0-cp39-abi3-manylinux_2_28_x86_64.whl (4.0 MB)
2024-08-05T11:25:08.1968457Z    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 166.4 MB/s eta 0:00:00
2024-08-05T11:25:08.2002903Z Downloading idna-3.7-py3-none-any.whl (66 kB)
2024-08-05T11:25:08.2081684Z Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
2024-08-05T11:25:08.2174474Z    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 856.7/856.7 kB 91.4 MB/s eta 0:00:00
2024-08-05T11:25:08.2200271Z Downloading urllib3-2.2.2-py3-none-any.whl (121 kB)
2024-08-05T11:25:08.2252883Z Downloading cffi-1.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (477 kB)
2024-08-05T11:25:08.2328722Z Downloading pycparser-2.22-py3-none-any.whl (117 kB)
2024-08-05T11:25:08.2740792Z Installing collected packages: urllib3, pycparser, idna, charset-normalizer, certifi, bcrypt, requests, cffi, pynacl, cryptography, paramiko
2024-08-05T11:25:09.0919359Z Successfully installed bcrypt-4.2.0 certifi-2024.7.4 cffi-1.16.0 charset-normalizer-3.3.2 cryptography-43.0.0 idna-3.7 paramiko-3.4.0 pycparser-2.22 pynacl-1.5.0 requests-2.32.3 urllib3-2.2.2
2024-08-05T11:25:09.2089023Z ##[group]Run python run.py
2024-08-05T11:25:09.2089567Z [36;1mpython run.py[0m
2024-08-05T11:25:09.2124356Z shell: /usr/bin/bash -e {0}
2024-08-05T11:25:09.2124867Z env:
2024-08-05T11:25:09.2125265Z   pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
2024-08-05T11:25:09.2125843Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib
2024-08-05T11:25:09.2126429Z   SSH_INFO: 
2024-08-05T11:25:09.2126755Z   PUSHPLUS_TOKEN: 
2024-08-05T11:25:09.2127049Z ##[endgroup]
2024-08-05T11:25:09.2839573Z /opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
2024-08-05T11:25:09.2841649Z   "cipher": algorithms.TripleDES,
2024-08-05T11:25:09.2968307Z /opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
2024-08-05T11:25:09.2970379Z   "class": algorithms.TripleDES,
2024-08-05T11:25:09.3869379Z Traceback (most recent call last):
2024-08-05T11:25:09.3880557Z   File "/home/runner/work/serv00-automation/serv00-automation/run.py", line 27, in <module>
2024-08-05T11:25:09.3881798Z     hosts_info = json.loads(ssh_info_str)
2024-08-05T11:25:09.3882431Z                  ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-05T11:25:09.3883747Z   File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/__init__.py", line 346, in loads
2024-08-05T11:25:09.4327069Z     return _default_decoder.decode(s)
2024-08-05T11:25:09.4327960Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-05T11:25:09.4329216Z   File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 337, in decode
2024-08-05T11:25:09.4330962Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-08-05T11:25:09.4333412Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-05T11:25:09.4334399Z   File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/json/decoder.py", line 355, in raw_decode
2024-08-05T11:25:09.4335428Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-08-05T11:25:09.4336186Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-08-05T11:25:09.4568840Z ##[error]Process completed with exit code 1.
2024-08-05T11:25:09.4658046Z Post job cleanup.
2024-08-05T11:25:09.5559199Z [command]/usr/bin/git version
2024-08-05T11:25:09.5596650Z git version 2.46.0
2024-08-05T11:25:09.5637883Z Temporarily overriding HOME='/home/runner/work/_temp/b59a1248-71d9-48f7-9f04-197f12912847' before making global git config changes
2024-08-05T11:25:09.5639029Z Adding repository directory to the temporary git global config as a safe directory
2024-08-05T11:25:09.5641756Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/serv00-automation/serv00-automation
2024-08-05T11:25:09.5675170Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-08-05T11:25:09.5705934Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-08-05T11:25:09.5948730Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-08-05T11:25:09.5969569Z http.https://github.com/.extraheader
2024-08-05T11:25:09.5980412Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-08-05T11:25:09.6011326Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-08-05T11:25:09.6528034Z Cleaning up orphan processes

原日志地址：https://productionresultssa6.blob.core.windows.net/actions-results/b6fe3b1e-39a9-4a6a-a27a-8cb9f5976dff/workflow-job-run-3d672287-6123-5b1a-c359-72ed73a8c169/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-05T11%3A35%3A34Z&sig=EB6DqCDuD0UU1D3IphLFaoFbgDTeSa4vRwDs9%2BV08zM%3D&ske=2024-08-05T22%3A37%3A22Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-05T10%3A37%3A22Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-05T11%3A25%3A29Z&sv=2024-05-04

**Comment by bin862324915** [comment]
请参照这里的格式[配置Secrets](https://github.com/bin862324915/serv00-automation?tab=readme-ov-file#%E9%85%8D%E7%BD%AEsecrets)
